USE [SIC]
GO

CREATE TABLE FIREBASE_TOKEN (
  ID                    int IDENTITY(1,1) PRIMARY KEY,
  CNPJ                  VARCHAR(20) NOT NULL,
  TOKEN                 VARCHAR(200) NOT NULL,
  DT_UPDATE             DATETIME DEFAULT CURRENT_TIMESTAMP,
);

CREATE INDEX IDX_FIREBASE_TOKEN_CNPJ ON FIREBASE_TOKEN (CNPJ);
