USE [SIC]
GO

CREATE TABLE SCCD_APP (
  ID                    int IDENTITY(1,1) PRIMARY KEY,
  TIPO                  VARCHAR(20) NOT NULL,
  DOCUMENTO             VARCHAR(20) NOT NULL,
  DT_UPLOAD             DATETIME DEFAULT CURRENT_TIMESTAMP,
  MOTORISTA             VARCHAR(60) NOT NULL,
  PLACAS                VARCHAR(60) NOT NULL,
  OBS                   VARCHAR(200) NOT NULL,
  OPERACAO              VARCHAR(20) NOT NULL,
  TIPOVEICULO           VARCHAR(20) NOT NULL,
  ARQUIVO               VARCHAR(150) NOT NULL,
  IMAGEM_ID             VARCHAR(20) NOT NULL,
  USUARIO               VARCHAR(60) NOT NULL,
  MATRICULA             VARCHAR(20) NOT NULL,
  DT_API                DATETIME DEFAULT CURRENT_TIMESTAMP,
  DT_SCCD               DATETIME
);

-- 27/01/2021
ALTER TABLE SCCD_APP ADD DESTINO VARCHAR(250);
ALTER TABLE SCCD_APP ADD FILIAL_APP VARCHAR(20);
ALTER TABLE SCCD_APP ADD FLAG_MYSQL INT DEFAULT 0;

-- 16/03/2021
CREATE INDEX IDX_SCCD_APP_DOCUMENTO ON SCCD_APP (DOCUMENTO);