SELECT SUBSTRING(DOCUMENTO,1,3) FILIAL,
       SUBSTRING(DOCUMENTO,5,12) NUMERO_ORDEM,
	   CONCAT(SUBSTRING(DOCUMENTO,1,3),SUBSTRING(DOCUMENTO,5,12)) CARTAFRETE, 
	   FILIAL_APP, 
	   MAX(DT_API) DATA,
	   OPERACAO, 
	   TIPOVEICULO TIPO, 
	   MAX(DT_SCCD) DATA_OPERACAO, 
	   USUARIO
 FROM SCCD_APP
 WHERE TIPO='CARTAFRETE' AND FLAG_MYSQL = 0 AND DOCUMENTO = 'MEO-6404'
 GROUP BY 
	   DOCUMENTO, 
	   FILIAL_APP, 
	   OPERACAO, 
	   TIPOVEICULO, 
	   USUARIO
 ;