SELECT A.*,CONCAT(CARTAFRETE,'_',FILIAL_APP,'_img_',FILE_SEQ) FILENAME FROM (
select ROW_NUMBER() OVER(PARTITION BY DOCUMENTO, OPERACAO, FILIAL_APP ORDER BY ID ASC) AS FILE_SEQ,
       SUBSTRING(DOCUMENTO,1,3) FILIAL,
       SUBSTRING(DOCUMENTO,1,3)+SUBSTRING(DOCUMENTO,5,16) CARTAFRETE,
	   OPERACAO,
	   FILIAL_APP,
	   ID,
	   DESTINO
from SCCD_APP b
) A
WHERE ID = 11780


   ---// C:\wamp64\www\sicnovo\carga\upload/ACJ/ACJ8125/DESCARGA/FOR/ACJ8125_FOR_img_1.jpg